# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/react/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4
    versioning-strategy: "lockfile-only"
