[tool.poetry]
name = "csgoinvshuffleweb"
version = "0.1.0"
description = "csgoinvshuffleweb"
authors = ["Jan Vollmer <zunder325@gmail.com>"]
license = "All Rights reserved"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
csgoinvshuffle = "^1.3.0"
requests = "^2.26.0"
flask-praetorian = {git = "https://github.com/dusktreader/flask-praetorian.git" }
Flask-Cors = "^3.0.10"
Flask-Caching = "^1.10.1"
redis = "^4.0.1"

[tool.poetry.dev-dependencies]
black = {version = "^21.12b0", allow-prereleases = true}
flake8 = "^4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
