[tool.poetry]
name = "csgo-inv-shuffle-web"
version = "0.1.0"
description = "csgo-inv-shuffle-web"
authors = ["Jan Vollmer <zunder325@gmail.com>"]
license = "All Rights reserved"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
csgoinvshuffle = "^1.1.3"
requests = "^2.26.0"
flask-praetorian = { git = "https://github.com/kreyoo/flask-praetorian.git" }

[tool.poetry.dev-dependencies]
fabric = "^2.6.0"
decorator = "^5.1.0"
black = {version = "^21.9b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
