name: Build & deploy

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  copy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.1
        env:
          key: master
          branches: release
          files: csgoinvshuffleweb pyproject.toml poetry.lock Procfile react
